apiVersion: v2
name: falco
description: A Helm chart for falco deployment
type: application
version: 9.0.0
appVersion: "9.0.0"
dependencies:
  - name: falco
    version:  "9.0.0"
    repository:  "https://falcosecurity.github.io/charts"
